homepage: "https://github.com/bernardoras/fuzzed_project_example"
language: python
primary_contact: "<primary_contact_email>"
main_repo: "https://github.com/bernardoras/fuzzed_project_example"
file_github_issue: true
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined